# Workflow written using the example here: https://github.com/arduino/report-size-deltas#workflow-triggered-by-pull_request-event
name: Compile Sketch

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'

env:
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          # Configure the action to search all folders under the root of the repository for sketches and compile them.
          sketch-paths: |
            - ./
          # Install library dependencies.
          libraries: |
            - name: IRremote
              version: 4.2.1
            - name: Servo
              version: 1.2.1
            - name: BasicLinearAlgebra
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      # This step is needed to pass the size data to the report job
      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          
  report:
    # Wait for the compile job to finish to get the data for the report
    needs: compile
    # Only run the job when the workflow is triggered by a pull request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # This step is needed to get the size data produced by the compile jobs
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
      
      - name: Write report
        uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
    
